//------------------------------------------------------------------
//-- File generated by RobustVerilog parser
//-- RobustVerilog version 1.5g (limited free version) Jul 5 2011
//-- Invoked Tue Mar 27 13:12:17 2012
//-- Source file: ahb_slave_mem.v
//-- Parent file: ahb_slave.v
//-- Project directory: /home/bgiorgos/Desktop/vlsi_project1/ahb_slave/trunk/run/
//-- Target directory: out/
//-- Command flags: /home/bgiorgos/Downloads/RobustVerilog_free1.5_lin/robust 
//-- www.provartec.com/edatools ... info@provartec.com
//------------------------------------------------------------------



  
module ahb_slave_mem (clk,reset,WR,RD,ADDR_WR,ADDR_RD,DIN,DOUT);

/*262144*/

   parameter                      MEM_WORDS = 64;
      
   input                          clk;
   input                          reset;
   input                          WR;
   input                          RD;
   input  [8:0]                  ADDR_WR;
   input  [8:0]                  ADDR_RD;
   input  [31:0]                  DIN;
   output [31:0]                  DOUT;

   reg [31:0]        	          DOUT;
   reg [31:0]           Mem[MEM_WORDS-1:0]; 
   
   always @(posedge clk)
     if (WR)
       Mem[ADDR_WR] <= DIN;
   
   always @(posedge clk or posedge reset)
     if (reset)
       DOUT <= {32{1'b0}};
     else if (RD) 
       DOUT <= Mem[ADDR_RD];

   
endmodule


